version: '2'

services:
  db:
    image: postgres:10.1-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=installs
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

#volumes:
#  postgres_data: